language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# install dependencies
install:
  - pip install coveralls pytest-cov flake8 pylint isort
  - pip install -e .

cache: pip

# run tests and linting
script:
  - py.test --cov-report term --cov=pylint_quotes
  - pylint pylint_quotes
  - flake8 --ignore E501 pylint_quotes
  - isort pylint_quotes -rc -c --diff

after_success:
  - coveralls
