language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# install dependencies
install:
  - pip install coveralls pytest-cov flake8 pylint isort
  - pip install -e .

cache: pip

# run tests and linting
script:
  - py.test --cov-report term --cov=pylint_quotes
  - pylint pylint_quotes
  - flake8 --ignore E501 pylint_quotes
  - isort pylint_quotes -rc -c --diff

after_success:
  - coveralls
